### ISSUE TITLE
Program Won't run. | Windows 7 x64 bit |

### ISSUE THREAD

**Issue by Hexxiiii** [p2r3/spplice#14]
![image](https://user-images.githubusercontent.com/106642288/202870977-0837f336-6d41-4ecd-a8ea-96bb4adf0f62.png)
For whatever reason, even when running with administer privileges, the program decides to instead show A white screen then close itself.
I tried to use the Installer And the actual "release" files, But the issue still occurred. I'm guessing this is most likely due to Windows 7 being outdated.

**Comment by p2r3** [comment]
Spplice does not support Windows 7. However, your specifc issue most likely comes from having Unicode characters in your username.

https://github.com/p2r3/spplice/issues/11
https://p2r3.com/spplice/faq
