### ISSUE TITLE
.exe broken

### ISSUE THREAD

**Issue by ARTUTTU** [p2r3/spplice#15]
when i stall it  and i try to open the .exe file it dosent work
no error
no nothing
just dosent start

**Comment by p2r3** [comment]
Please provide some system information. What operating system is this? What version?

**Comment by ARTUTTU** [comment]
windows 11

**Comment by p2r3** [comment]
To clarify, are we talking about the installer or the Spplice executable itself? If it's the latter, this sounds a lot like another common issue - does your Windows username contain Unicode characters?

**Comment by ARTUTTU** [comment]
the executable

**Comment by ARTUTTU** [comment]
what is an unicode character?

**Comment by p2r3** [comment]
By Unicode character I mean anything that doesn't fit within the Latin alphabet. Or, in other words, anything that isn't English letters or numbers. If that's the case, the only real solution is to create a new Windows user account and install Spplice there.

**Comment by ARTUTTU** [comment]
accent marks counts?

**Comment by p2r3** [comment]
Yes, they do.

**Comment by ARTUTTU** [comment]
thanks

**Comment by ARTUTTU** [comment]
also...
i love your videos
