### ISSUE TITLE
Spplice shuts down immediatly

### ISSUE THREAD

**Issue by Filval387** [p2r3/spplice#16]
Everytime I launch spplice, the window opens but closes before showing anything. I've tried to launch it with administrator to see if it changed something but it still closes. I don't know if I'm doing something wrong or if the program is just having an issue with my computer.

**Comment by p2r3** [comment]
First, take a look at this: https://p2r3.com/spplice/faq/

If your issue is unrelated to anything mentioned there, give us your OS version and we'll work from there.

**Comment by Filval387** [comment]
The issue was with my computer's username. I've managed to change my username to not contain those characters and it worked. Thanks!
