### ISSUE TITLE
steam is not running

### ISSUE THREAD

**Issue by KaziiTheAvali** [p2r3/spplice#19]
![image](https://github.com/p2r3/spplice/assets/87594664/f61ffcac-3aeb-4480-9471-a81594e2bb63)
it says steam is not running after showing the portal 2 intro loop
(linux)
i should note i have checked the steam app path and i think its right (not fully shure)

**Comment by p2r3** [comment]
That... looks like the Windows prompt - are you sure you haven't enabled Proton for whatever reason? Can you also confirm that a vanilla game launch doesn't throw this?

**Comment by KaziiTheAvali** [comment]
i forgot i left this. yes the vanilla game launch did throw this however proton wasnt enabled. i do tend to enable proton launch the game and then disable proton if crashes happen. it was however an easy fix of fully deleting all steam and steam related folders and then reinstalling steam
