### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Badpoolinator** [p2r3/spplice#3]
When I try to install a package, it just says Installation failed, Failed to download package

![image](https://user-images.githubusercontent.com/78545688/192155803-ff8413a5-a665-4d2d-8895-b9b21a257251.png)

Any fixes?

**Comment by p2r3** [comment]
This indicates that `curl` exited with a non-zero error code.

First, make sure your system has the `curl` command line utility. And second, check if it works when downloading from an HTTP server to a local directory with the `-o` switch.

This might also be a network issue, but without additional information, I cannot say for sure.
