### ISSUE TITLE
Won't open Portal 2

### ISSUE THREAD

**Issue by ShadowNinja1246** [p2r3/spplice#4]
Mod installing works as normal (I think), but when it gets to the "Starting Portal 2" phase, it gets stuck and Portal 2 won't open. Spplice worked fine earlier today, but I accidentally closed the launcher while the Rocket Launcher mod was open, if that helps. 

I have tried uninstalling and reinstalling Spplice, clearing the mods, verifying Portal 2's files, and restarting my computer. Any help would be greatly appreciated. Thanks!
![spplice_issue](https://user-images.githubusercontent.com/114453902/192409870-f1cc20fd-f12f-4c4d-a817-e6dc928db8ce.PNG)
(This is what Spplice has looked like for the past 10 minutes or so.)

**Comment by p2r3** [comment]
This (or a similar issue) has been resolved on the newest update.

If the problem persists, open another issue with more information on the current OS and Steam and Portal 2 installation paths.
