### ISSUE TITLE
Steam Deck compatible version?

### ISSUE THREAD

**Issue by DraconicBlaze28** [p2r3/spplice#5]
The Steam Deck doesn't seem to be able to run the Linux version, and using the windows version through Proton wouldn't work, since Portal would be in a different prefix. Would it be possible to make a Steam Deck compatible version?

**Comment by p2r3** [comment]
Just like any other Linux application, Spplice runs natively on Linux given the right dependencies, which in this case is `gtk-webkit2` and can be acquired from the AUR.

Marking this issue as resolved due to compatibility already existing.

**Comment by DraconicBlaze28** [comment]
Ah. Sorry, I'm still pretty new to Linux. Thank you

**Comment by DraconicBlaze28** [comment]
As far as I can tell, there doesn't seem to be a way to install webkit on Steam Deck
