### ISSUE TITLE
Won't open Portal 2 (more information)

### ISSUE THREAD

**Issue by ShadowNinja1246** [p2r3/spplice#7]
Same thing as before, upon launching a mod it does all the normal stuff up until the "starting Portal 2" part, then it stops. I redownloaded the installer from the website https://p2r3.com/spplice/ as I assumed that the newest version would be there. 

My OS is Windows 10 home edition, version 21H2, OS build 19044.2006
64-bit operating system, x64-based processor

Steam installation path: C:\Program Files (x86)
Portal 2 installation path: C:\Program Files (x86)\Steam\steamapps\common

**Comment by p2r3** [comment]
Is Steam open and Portal 2 closed when loading the package? Spplice currently cannot close an active game, so make sure Portal 2 is closed before you start it.

Another common issue is that Steam often silently displays a notification about cloud save discrepancy in the background, which prevents the game from opening until this notification is closed. Try opening your Steam library when Spplice tries to start the game.

**Comment by ShadowNinja1246** [comment]
It seems that the new release has fixed the problem. I will let you know if the problem reappears.
