### ISSUE TITLE
portal 2 doesnt open

### ISSUE THREAD

**Issue by NULL64YT** [p2r3/spplice#8]
i saw the other issue on portal 2 not opening when installing a mod, and i tried all of the options presented and it didnt work.

i made sure im not running p2 in any sense while installing a mod, didnt work

i tried reinstalling spplice, never opened p2

i tried opening my steam library, didnt open p2

my OS is Windows 10, i have a 64-bit operating system

my steam installation path is C:\Program Files (x86)

and my p2 installation path is C:\Program Files (x86)\Steam\steamapps\common

please help, i have no idea what i could be doing wrong

**Comment by p2r3** [comment]
Some users have had better luck when starting Spplice as Administrator. If that doesn't work, try running Spplice with Steam fully closed.

If _that_ doesn't work, join the Discord server linked in the description of videos. We'll provide you with an alternative version that usually works in these cases.

**Comment by NULL64YT** [comment]
starting as administrator worked, thank you so much
